#general:
#  # Whether to automatically focus windows underneath the cursor.
#  focus_follows_cursor: false
#
#  # Whether to jump the cursor between windows focused by the WM.
#  cursor_follow_focus: false
#
#  # Whether to switch back and forth between the previously focused workspace
#  # when focusing the current workspace.
#  toggle_workspace_on_refocus: true
#
#  # Whether to show floating windows as always on top.
#  show_floating_on_top: true
#
#  # Amount to move floating windows by (eg. when using `alt+<hjkl>` on a floating window)
#  floating_window_move_amount: "5%"
#
#  # *Strongly* recommended to set to 'false'. Whether to globally enable/disable
#  # window transition animations (on minimize, close, etc). Set to 'unchanged'
#  # to make no setting changes.
#  window_animations: "false"
#
#gaps:
#  # Gap between adjacent windows.
#  inner_gap: "5px"
#
#  # Gap between windows and the screen edge.
#  outer_gap: "5px"
#
## Highlight active/inactive windows with a colored border.
## ** Exclusive to Windows 11 due to API limitations.
#focus_borders:
#  active:
#    enabled: true
#    color: "#00FFFF"
#
#  inactive:
#    enabled: false
#    color: "#ff0000"
#
#bar:
#  height: "25px"
#  position: "top"
#  opacity: 1.0
#  background: "#20242cc4"
#  foreground: "#ffffff"
#  font_family: "FiraCode Nerd Font"
#  font_size: "13px"
#  padding: "4px 6px"
#  offset_x: "0"
#  offset_y: "0"
#  border_radius: "0"
#  component_separator:
#    label: " | "
#  components_left:
#    - type: "workspaces"
#      focused_workspace_background: "#5cb85c "
#      displayed_workspace_background: "#00000033"
#      default_workspace_background: "transparent"
#  components_center:
#    - type: "window title"
#  components_right:
#    - type: "system tray"
#    # - type: "tiling direction"
#    #   label_horizontal: "⮂"
#    #   label_vertical: "⮁"
#    #   background: "#ffffff33"
#    #   margin: "0 4px"
#    #   padding: "0 8px"
#    # - type: "binding mode"
#    #   background: "#ffffff33"
#    #   margin: "0 4px 0 0"
#    #   padding: "0 8px"
#    # - type: "cpu"
#    #   label: "CPU: {percent_usage}%"
#    #   # How often this counter is refreshed.
#    #   refresh_interval_ms: 1000
#    # - type: "gpu"
#    #   label: "GPU: {percent_usage}%"
#    #   # How often this counter is refreshed.
#    #   refresh_interval_ms: 1000
#    # - type: "memory"
#    #   label: "RAM: {percent_usage}%"
#    #   # How often this counter is refreshed.
#    #   refresh_interval_ms: 1000
#    - type: "battery"
#    - type: "clock"
#      # Documentation on formatting date/time string:
#      # https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings
#      time_formatting: "HH:mm ddd d MMM"
#
#workspaces:
#  - name: "1"
#    # Optional override for the workspace label in the bar. Does not need to be unique.
#    display_name: "1  Browser"
#    # Optionally prevent workspace from being deactivated when empty.
#    keep_alive: true
#  - name: "2"
#    display_name: "2 Pycharm"
#    keep_alive: true
#  - name: "3"
#    display_name: "3  Explorer"
#    keep_alive: true
#  - name: "4"
#    display_name: "4: Text Editor"
#    keep_alive: true
#  - name: "5"
#    display_name: "5  Social"
#    keep_alive: true
#  - name: "6"
#    display_name: "6  Gaming"
#    keep_alive: true
#  - name: "7"
#  - name: "8"
#  - name: "9"
#
#window_rules:
#  # Task Manager requires admin privileges to manage and should be ignored unless running
#  # the WM as admin.
#  - command: "ignore"
#    match_process_name: "/Taskmgr|ScreenClippingHost/"
#
#  # Launches system dialogs as floating by default (eg. File Explorer save/open dialog).
#  - command: "set floating"
#    match_class_name: "#32770|Taskmgr"
#binding_modes:
#  - name: "resize"
#    keybindings:
#      # Resize focused window by a percentage or pixel amount.
#      - command: "resize width -2%"
#        bindings: ["H", "Left"]
#      - command: "resize width +2%"
#        bindings: ["L", "Right"]
#      - command: "resize height +2%"
#        bindings: ["K", "Up"]
#      - command: "resize height -2%"
#        bindings: ["J", "Down"]
#      # Press enter/escape to return to default keybindings.
#      - command: "binding mode none"
#        bindings: ["Escape", "Enter"]
#
#keybindings:
#  # Shift focus in a given direction.
#  - command: "focus left"
#    bindings: ["Alt+H", "Alt+Left"]
#  - command: "focus right"
#    bindings: ["Alt+L", "Alt+Right"]
#  - command: "focus up"
#    bindings: ["Alt+K", "Alt+Up"]
#  - command: "focus down"
#    bindings: ["Alt+J", "Alt+Down"]
#
#  # Move focused window in a given direction.
#  - command: "move left"
#    bindings: ["Alt+Shift+H", "Alt+Shift+Left"]
#  - command: "move right"
#    bindings: ["Alt+Shift+L", "Alt+Shift+Right"]
#  - command: "move up"
#    bindings: ["Alt+Shift+K", "Alt+Shift+Up"]
#  - command: "move down"
#    bindings: ["Alt+Shift+J", "Alt+Shift+Down"]
#
#  # Resize focused window by a percentage or pixel amount.
#  - command: "resize width -2%"
#    binding: "Alt+U"
#  - command: "resize width +2%"
#    binding: "Alt+P"
#  - command: "resize height +2%"
#    binding: "Alt+O"
#  - command: "resize height -2%"
#    binding: "Alt+I"
#
#  # As an alternative to the resize keybindings above, resize mode enables resizing via
#  # HJKL or arrow keys. The binding mode is defined above with the name "resize".
#  - command: "binding mode resize"
#    binding: "Alt+R"
#
#  # Change tiling direction. This determines where new tiling windows will be inserted.
#  - command: "tiling direction toggle"
#    binding: "Alt+V"
#
#  # Change focus between floating / tiling windows.
#  - command: "focus mode toggle"
#    binding: "Alt+Ctrl+Space"
#
#  # Change the focused window to be floating / tiling.
#  - command: "toggle floating"
#    binding: "Alt+Shift+Space"
#
#  # Change the focused window to be maximized / unmaximized.
#  - command: "toggle maximized"
#    binding: "Alt+F"
#
#  # Minimize focused window.
#  - command: "set minimized"
#    binding: "Alt+M"
#
#  # Close focused window.
#  - command: "close"
#    binding: "Alt+Shift+Q"
#
#  # Kill GlazeWM process safely.
#  - command: "exit wm"
#    binding: "Alt+Shift+E"
#
#  # Re-evaluate configuration file.
#  - command: "reload config"
#    binding: "Alt+Shift+R"
#
#  # Launch CMD terminal (alternatively `exec wt` or `exec %ProgramFiles%/Git/git-bash.exe`
#  # to start Windows Terminal and Git Bash respectively.
#  - command: "exec wt"
#    binding: "Alt+T"
#
#  # Focus the workspace that last had focus.
#  - command: "focus workspace recent"
#    binding: "Alt+Y"
#
#  # Focus the next/previous workspace defined in `workspaces` config.
#  - command: "focus workspace next"
#    binding: "Alt+T"
#  - command: "focus workspace prev"
#    binding: "Alt+Shift+T"
#
#  # Change focus to a workspace defined in `workspaces` config.
#  - command: "focus workspace 1"
#    binding: "Alt+1"
#  - command: "focus workspace 2"
#    binding: "Alt+2"
#  - command: "focus workspace 3"
#    binding: "Alt+3"
#  - command: "focus workspace 4"
#    binding: "Alt+4"
#  - command: "focus workspace 5"
#    binding: "Alt+5"
#  - command: "focus workspace 6"
#    binding: "Alt+6"
#  - command: "focus workspace 7"
#    binding: "Alt+7"
#  - command: "focus workspace 8"
#    binding: "Alt+8"
#  - command: "focus workspace 9"
#    binding: "Alt+9"
#
#  # Move focused workspace to a monitor in a given direction.
#  - command: "move workspace left"
#    binding: "Alt+A"
#  - command: "move workspace right"
#    binding: "Alt+F"
#  - command: "move workspace up"
#    binding: "Alt+D"
#  - command: "move workspace down"
#    binding: "Alt+S"
#
#  # Move focused window to a workspace defined in `workspaces` config.
#  - commands: ["move to workspace 1"] #, "focus workspace 1"]
#    binding: "Alt+Shift+1"
#  - commands: ["move to workspace 2"] #, "focus workspace 2"]
#    binding: "Alt+Shift+2"
#  - commands: ["move to workspace 3"] #, "focus workspace 3"]
#    binding: "Alt+Shift+3"
#  - commands: ["move to workspace 4"] #, "focus workspace 4"]
#    binding: "Alt+Shift+4"
#  - commands: ["move to workspace 5"] #, "focus workspace 5"]
#    binding: "Alt+Shift+5"
#  - commands: ["move to workspace 6"] #, "focus workspace 6"]
#    binding: "Alt+Shift+6"
#  - commands: ["move to workspace 7"] #, "focus workspace 7"]
#    binding: "Alt+Shift+7"
#  - commands: ["move to workspace 8"] #, "focus workspace 8"]
#    binding: "Alt+Shift+8"
#  - commands: ["move to workspace 9"] #, "focus workspace 9"]
#    bindings: ["Alt+Shift+9"]
#
#window_rules:
#  # Command to run. Use `commands` to specify an array of commands to run in sequence.
#  # To find an app : open it then go to task manager and show its process name. The process name is case sensitive
#  # 1 browser
#  - command: "move to workspace 1"
#    match_process_name: "msedge"
#    match_process_name: "brave"
#  # 2 pycharm
#  - command: "move to workspace 2"
#    # Process name to match exactly.
#    match_process_name: "pycharm64"
#  # 2 file explorer, terminal,
#  - command: "move to workspace 3"
#    match_process_name: "explorer|wt"
#
#  # To prevent the WM from managing an app, use the "ignore" command.
#  - command: "ignore"
#    match_process_name: "notepad"
#
#  # 4 text editors : sublime text, word, bloc note..
#  - command: "move to workspace 4"
#    match_process_name: "sublime_text"
#
#  # 5 Social
#  - command: "move to workspace 5"
#    match_process_name: "Messenger"
#  - command: "move to workspace 5"
#    match_process_name: "messenger"
#  - command: "move to workspace 5"
#    match_process_name: "Discord"
#
#  # 6 gaming
#  - command: "move to workspace 6"
#    match_process_name: "steam"
#  - command: "move to workspace 6"
#    match_process_name: "Steam"
#  - command: "move to workspace 6"
#    match_process_name: "steamwebhelper.exe"
#  - command: "move to workspace 6"
#    match_process_name: "steamwebhelper"
#  - command: "move to workspace 6"
#    match_process_name: "Epic"
#  - command: "move to workspace 6"
#    match_process_name: "epic"
