packages:
  ubuntu:
    apt:
      core:
        - git
        - curl
        - zsh
      terminal_tools:
        - bat
        - fzf
        - btop
        - neofetch
        - lsd
    snap:
      apps:
        - code
  darwin:
    brew:
      core:
        - git
        - zsh
    cask:
      apps:
        - brave-browser
        - raycast
        - ghostty
        - jordanbaird-ice # Menu bar management tool
        - shottr
        - swift-quit
        - alt-tab
        - anydesk
        - obsidian
        - zed
        - discord
  arch:
    yay:
      core:
        - git
        - curl
        - zsh
      terminal_tools:
        - bat
        - fzf
        - btop
        - neofetch
        - eza
        - lsd
        - ripgrep
        - tldr
        - zoxide
        - docker
        - lazygit
        - lazydocker
        - tmux
        - neovim
        - python
        - bpytop
        - fd
        - opencode
      apps:
        - brave-browser
        - vicinae
        - ghostty
        - steam
        - obsidian
        - vlc
        - wine
        - vesktop
  windows:
    winget:
      Browsers:
        - Brave.Brave
        - ImputNet.Helium
        - Mozilla.Firefox
        - Microsoft.Edge
        - Zen-Team.Zen-Browser
      Messaging:
        - Discord.Discord
        - WhatsApp.WhatsApp
        - Viber.Viber
        - Telegram.TelegramDesktop
      Meetings:
        - Zoom.Zoom
        - Microsoft.Teams
      Media:
        - Stremio.Stremio.Beta
        - VideoLAN.VLC
        - Spotify.Spotify
        - Apple.AppleMusic
      Gaming:
        - Valve.Steam
        - EpicGames.EpicGamesLauncher
        - Nvidia.GeForceExperience
        - Ubisoft.Connect
        - SideQuestVR.SideQuest
      Drives:
        - Google.GoogleDrive
        - Microsoft.OneDrive
        - Apple.iCloud
      Editing:
        - OBSProject.OBSStudio
        - ByteDance.CapCut
        - Microsoft.Clipchamp
        - Canva.Canva
      Text Editors:
        - Obsidian.Obsidian
        - Notion.Notion
        - PDFgear.PDFgear
      Dev_tools:
        - Microsoft.WindowsTerminal
        - JetBrains.Toolbox
        - Comfy.ComfyUI-Desktop
        - Docker.DockerDesktop
        - Microsoft.VisualStudioCode
        - MongoDB.Compass.Full
      Devices Software:
        - Logitech.GHUB
        - Brother.iPrintScan
        - SteelSeries.GG
        - SteelSeries.SteelSeriesEngine
      Utilities:
        - glzr-io.glazewm
        - NordVPN.NordVPN
        - qBittorrent.qBittorrent
        - Microsoft.PowerToys
        - ShareX.ShareX
        - Ookla.Speedtest.Desktop
        - Microsoft.BingWallpaper
        - File-New-Project.EarTrumpet
        - RevoUninstaller.RevoUninstaller
        - REALiX.HWiNFO
        - touchbyte.PhotoSync
        - AnyDesk.AnyDesk
        - BinaryFortress.DisplayFusion
        - RARLab.WinRAR
      Winget UI Manager:
        - MartiCliment.UniGetUI

    msstore:
      Devices Software:
        - msi center
      Utilities:
        - "ChatGPT"
    webinstall:
      Devices Software:
        - '[Ryzen Master](https://www.amd.com/fr/products/software/ryzen-master.html#download)'
        - '[Turtle Beach](https://support.turtlebeach.com/s/downloads?language=fr#)'
